### PR TITLE
Allow processors to rename file attachments

### PR DESCRIPTION
**Pull request by JPrevost**
Why are these changes being introduced:

* Duplicate filenames attached to a thesis cannot be preserved
* Sometimes we get duplicate filenames attached to a thesis
* We did not have a way to rename filenames in the application

Relevant ticket(s):

* https://mitlibraries.atlassian.net/browse/ETD-643

How does this address that need:

* Adds a form that allows processors to rename a file attachment

Document any side effects to this change:

* ability model initialize class was auto updated by rubocop to use a guard clause

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [ ] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [ ] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Review by jazairi — COMMENTED** [review]
The code looks good, and I confirmed the changes locally (both renaming files in the UI and confirming checksums in SIPs). Part of me wants to add this to the admin UI, but another, more confident part of me feels like it's not worth the trouble of custom fields/views.

One thing I'd like to consider, either in this ticket or a subsequent one, is whether we should be handling naming conflicts in the File Controller. As written, processors can rename a file to have the same filename as other file on that thesis. This feels like a very remote edge case, though, and it may be enough that the preservation job will fail with duplicate filenames. What do you think?

**Comment by JPrevost** [comment]
@jazairi good idea on preventing the creation of problems by checking for duplicate names and possibly some other edge cases that weren't considered when doing this initial work. Thanks!

**Comment by jazairi** [comment]
@JPrevost No problem! Just noticed that I didn't officially approve this, so I'll do that now in case you'd like us to handle that in follow-on work. (I haven't thought about it too deeply, but it may end up being a reasonable chunk of work.)

**Review by jazairi — APPROVED** [review]

**Comment by JPrevost** [comment]
@jazairi I've added handling for two edge cases which led to significant reworking of the new controller so it may feel like an entirely new review...

**Review by jazairi — APPROVED** [review]
Good ol' report tests. This looks good, despite my English-major-induced shudder at the word "prerename." Thanks for making this significant change prior to merging.

**Pull request merged**
