### PR TITLE
Create a basic UI for managing Hold records

### PR DESCRIPTION
**Pull request by matt-bernhardt**
#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [x] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [x] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Review by JPrevost — COMMENTED** [review]
Would you mind adding Holds to the Thesis Show and List dashboards? While semi out of scope, I feel like it would be super useful to be able to see the Holds in those locations. It may be easiest to chat on Slack or Zoom to confirm what I'm suggesting.

**Review by JPrevost — APPROVED** [review]

**Comment by matt-bernhardt** [comment]
Leaving this comment so future-me doesn't accidentally merge this too early - we are waiting now for stakeholder review of these changes. Once that happens (either via Slack or the Jira ticket), this can merge.

**Comment by matt-bernhardt** [comment]
I've rebased this branch to the end of `main` after #589 merged. Based on Mikki's comments in the Jira ticket, I _think_ we have stakeholder approval (there's a feature she wants on the Holds table which we'll need to create a ticket for).

@JPrevost can you look at the last commit in this branch? This was the adjustment made based on Mikki's earlier feedback in the Jira ticket, and was not in the changeset that you reviewed.

**Comment by JPrevost** [comment]
@matt-bernhardt looks good

**Pull request merged**
