### PR TITLE
Fix date parsing bug in registrar import

### PR DESCRIPTION
**Pull request by hakbailey**
Why these changes are being introduced:
It turns out there are multiple ways to export files from BrioQuery
that result in slightly differently-formatted graduation date fields.
The method we have confirmed we will use going forward is different
from what was used in testing so the graduation date parsing needs
a very minor update.

How this addresses that need:
* Updates the graduation date parsing in Registrar import to expect
  a date string in the format mm/dd/yyyy.
* Updates all relevant fixture files to match the expected date format.

Side effects of this change:
None

Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ETD-226

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [x] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [x] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
Side note - the deploy failure here is unrelated to anything in this PR. There's a dependency of Rails that has been having a moment over the last few days, and we're dealing with the fallout (along with lots of other sites).

**Review by matt-bernhardt — APPROVED** [review]
These changes seem fairly straightforward to my eye. The tests still pass locally, and thanks to the ongoing Mimemagic debacle we don't yet have a review app to consult.

As a result, I'm approving this change but there's a greater-than-usual risk that we're missing something because there's no review app. I guess we will find out.

:shipit:

**Comment by JPrevost** [comment]
@hakbailey can you rebase this to confirm the build works in Heroku now that we've landed a fix for a dependency that was broken before you merge?

**Comment by hakbailey** [comment]
> @hakbailey can you rebase this to confirm the build works in Heroku now that we've landed a fix for a dependency that was broken before you merge?

@JPrevost Done! Lmk if I need to do anything else or if/when this is good to go.

**Pull request merged**
