### PR TITLE
valid json ftw

### PR DESCRIPTION
**Pull request by JPrevost**
## Status
**READY**

#### What does this PR do?

Apparently valid JSON is a good thing.

#### How can a reviewer manually see the effects of these changes?

If the PR build works, it work!

#### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/TI-36

#### Requires Database Migrations?
NO

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by thatandromeda** [comment]
The PR build does not work :(

**Comment by thatandromeda** [comment]
I think it's failing because it lacks IDP metadata. And IIRC there are valid reasons not to have that on PR builds, but there's a devise config thing that dies without it.

**Comment by thatandromeda** [comment]
Anyway, if the goal of this PR is to have valid JSON I'm good with it, but if the goal is to fix PR builds (which I think is the better goal), there is more work to be done.

**Comment by JPrevost** [comment]
This PR is flagged as In Development ;) I know it's broke but went to lunch when it was clear it was not a quick fix lol.

**Comment by JPrevost** [comment]
@thatandromeda should be working now after updating the match pattern.

**Pull request merged**
